const news=[['TRANSFER','Star forward completes a blockbuster move ahead of the new season','2h ago','⚡'],['CHAMPIONS LEAGUE','Five moments that changed a dramatic European night','4h ago','🏆'],['PREMIER LEAGUE','Managers reveal their biggest plans for the season','6h ago','🎙️'],['WORLD CUP','The young stars ready to take over international football','8h ago','🌍'],['TACTICS','Why high pressing is changing modern football','10h ago','🧠'],['MATCHDAY','Everything you need to know before kickoff','12h ago','🔥']];
const videos=[['Best goals of the week — unbelievable finishes','03:42','▶'],['Top 10 skills that broke the internet','05:18','▶'],['Last-minute winners you have to see','04:11','▶'],['Inside the dressing room after a huge win','06:02','▶'],['Young talents to watch this season','03:35','▶'],['The craziest football celebrations','04:48','▶']];
const matches=[['Real Madrid','Barcelona','20:00'],['Manchester City','Liverpool','21:00'],['Bayern Munich','Dortmund','21:30'],['Inter Milan','AC Milan','22:00']];
const newsGrid=document.querySelector('#newsGrid');news.forEach(n=>newsGrid.innerHTML+=`<article class="news-card"><div class="thumb">${n[3]}</div><div class="body"><div class="tag">${n[0]}</div><h3>${n[1]}</h3><div class="meta">${n[2]} · FootballHub</div></div></article>`);
const videoGrid=document.querySelector('#videoGrid');videos.forEach(v=>videoGrid.innerHTML+=`<article class="video"><div class="video-cover"><div class="play">${v[2]}</div><span class="duration">${v[1]}</span></div><div class="video-body"><h3>${v[0]}</h3></div></article>`);
const matchesGrid=document.querySelector('#matchesGrid');matches.forEach(m=>matchesGrid.innerHTML+=`<div class="match"><div class="teams">${m[0]} <span>vs</span> ${m[1]}</div><div class="time">${m[2]} · Today</div></div>`);
const modal=document.querySelector('#loginModal');document.querySelector('#loginBtn').onclick=()=>modal.classList.remove('hidden');document.querySelector('#closeModal').onclick=()=>modal.classList.add('hidden');document.querySelector('#searchBtn').onclick=()=>{const q=prompt('Search FootballHub');if(q)showToast('Search is ready — connect your content API to enable results.');};document.querySelector('#newsletterForm').onsubmit=e=>{e.preventDefault();showToast('Thanks! You are subscribed.');e.target.reset()};
let supabaseClient=null;if(window.SUPABASE_URL&&window.SUPABASE_ANON_KEY&&window.supabase){supabaseClient=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY)}
const authForm=document.querySelector('#authForm');authForm.onsubmit=async e=>{e.preventDefault();if(!supabaseClient){showToast('Add your Supabase URL and anon key in js/config.js first.');return}const email=document.querySelector('#email').value,password=document.querySelector('#password').value;const {error}=await supabaseClient.auth.signInWithPassword({email,password});document.querySelector('#authStatus').textContent=error?error.message:'Signed in successfully!';if(!error)setTimeout(()=>modal.classList.add('hidden'),800)};
document.querySelector('#signupBtn').onclick=async()=>{if(!supabaseClient){showToast('Add your Supabase URL and anon key in js/config.js first.');return}const email=document.querySelector('#email').value,password=document.querySelector('#password').value;if(!email||!password){document.querySelector('#authStatus').textContent='Enter email and password first.';return}const {error}=await supabaseClient.auth.signUp({email,password});document.querySelector('#authStatus').textContent=error?error.message:'Account created. Check your email if confirmation is enabled.'};
function showToast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
